import {RoomType} from '../types/roomType.ts';

export const Rooms: RoomType[] = [
  {label: 'PROJECT3', value: 'PROJECT3'},
  {label: 'PROJECT4', value: 'PROJECT4'},
  {label: 'LAB 1', value: 'LAB1'},
  {label: 'LAB 2', value: 'LAB2'},
  {label: 'LAB 3, 4', value: 'LAB3_4'},
  {label: 'LAB 5', value: 'LAB5'},
  {label: 'LAB 6', value: 'LAB6'},
  {label: 'LAB 7', value: 'LAB7'},
  {label: 'LAB 8', value: 'LAB8'},
  {label: 'LAB 9', value: 'LAB9'},
  {label: 'LAB 10', value: 'LAB10'},
  {label: 'LAB 11', value: 'LAB11'},
  {label: '서버실', value: 'SERVER'},
  {label: 'LAB 12', value: 'LAB12'},
  {label: 'LAB 13', value: 'LAB13'},
  {label: 'LAB 14', value: 'LAB14'},
  {label: 'LAB 15, 16', value: 'LAB15_16'},
  {label: 'LAB 17, 18', value: 'LAB17_18'},
  {label: 'LAB 19, 20', value: 'LAB19_20'},
  {label: 'LAB 21, 22', value: 'LAB21_22'},
  {label: 'PROJECT5', value: 'PROJECT5'},
  {label: 'PROJECT6', value: 'PROJECT6'},
  {label: '프린터실', value: 'PRINTER_MAKER'},
];
